version: '3.8'
services:
  app:
    build:
      context: .
    container_name: nest-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/nest-db
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
